name: fluxstore
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  hive: ^2.2.3
  pinput: ^5.0.1
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sidebar/
