name: Build and Push Docker Image

on:
  push:
    paths:
      - "fluxstore-backend/**"
    branches:
      - main # or your deployment branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up environment variables
        run: |
          echo "DATABASE_CONNECTION_STRING=${{ secrets.DATABASE_CONNECTION_STRING }}" >> fluxstore-backend/.env

      - name: Build Docker image
        run: docker build -t michaelkingsec/fluxstore-backend ./fluxstore-backend

      - name: Push Docker image
        run: docker push michaelkingsec/fluxstore-backend
